### ISSUE TITLE
Does not import on py3.8/Windows b/c `time.clock` is removed

### ISSUE THREAD

**Issue by asodeur** [crossbario/zlmdb#18]
* ZLMDB version: * (?)
* Python version: 3.8
* Operating System: Windows

`zlmdb` will not import on Python 3.8/Windows since `time.clock` has been removed. (`time.clock`  has been deprecated since 3.3.) As far as I can tell `time.perf_counter` should be used for Python >= 3.3 esp since it works for Windows and Unix. 

The import error:
```python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlmdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\zlmdb\zlmdb\__init__.py", line 102, in <module>
    from ._transaction import Transaction, TransactionStats, walltime
  File "...\zlmdb\zlmdb\_transaction.py", line 39, in <module>
    walltime = time.clock
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by oberstet** [comment]
I don't have windows, so I can't test: does the following work on windows?

https://github.com/crossbario/txaio/blob/master/txaio/_util.py

```
(cpy381_5) oberstet@intel-nuci7:~/scm/crossbario/xbr-www$ python -V
Python 3.8.1
(cpy381_5) oberstet@intel-nuci7:~/scm/crossbario/xbr-www$ python
Python 3.8.1 (default, Jan 14 2020, 17:03:33) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from txaio import time_ns, perf_counter_ns
>>> 
```

because if it does, then we'd like to use that instead:

```python
from txaio import time_ns as walltime
```

**Comment by asodeur** [comment]
`from txaio import time_ns, perf_counter_ns` works on Windows for py36 - py38. Currently I do not have py35 installed.

**Comment by oberstet** [comment]
ok, thanks!

even though zlmdb claims support for py3.5+, what you tested (thanks again!) is good enough for me .. it "should work" (well, I know it does on other platforms).

means: I'd go for `txaio.time_ns`

walltime is used here:

```
oberstet@intel-nuci7:~/scm/crossbario/zlmdb$ find zlmdb -name "*.py" -exec grep -Hi "walltime" {} \;
zlmdb/__init__.py:from ._transaction import Transaction, TransactionStats, walltime
zlmdb/__init__.py:    'walltime',
zlmdb/_transaction.py:    walltime = time.clock
zlmdb/_transaction.py:    _ = walltime()  # this starts wallclock
zlmdb/_transaction.py:    walltime = time.time
zlmdb/_transaction.py:        self._started = walltime()
zlmdb/_transaction.py:            return walltime() - self._started
zlmdb/_transaction.py:        self._started = walltime()
zlmdb/tests/test_flatbuffers.py:                    started = zlmdb.walltime()
zlmdb/tests/test_flatbuffers.py:                    duration = zlmdb.walltime() - started
oberstet@intel-nuci7:~/scm/crossbario/zlmdb$ 
```

the first one can directly use `time_ns` - this changes the semantics of `TransactionStats.duration` to returning ns. that is fine. no harm. makes sense anyways.

the second one `zlmdb/tests/test_flatbuffers.py` should also use `txaio.time_ns`, but compute test duration into ms https://github.com/crossbario/zlmdb/blob/10f81a9d5d11cc363e62809124de85fb3c30a7f4/zlmdb/tests/test_flatbuffers.py#L130

if you change your PR accordingly, I'll merge it pronto - or I can do it .. sometime .. overload;)
