### ISSUE TITLE
pytest-runner required for install

### ISSUE THREAD

**Issue by vaibhav-rbs** [crossbario/zlmdb#35]
* ZLMDB version:20.4.1
* Python version:3.6.8
* Operating System:Redhat 8 Linux

### Description
I am trying to install crossbar.io (20.7.1) using an internal pypi server. zlmdb fails to install because of missing pytest-runner pkg, it should not fail as you can see in logs that internal pypi server has access to pytest-runner==5.2 so as a part of the requirements-min.txt, crossbar.io install should install zlmdb  20.4.1 as well. Linux server where I am trying to install crossbar.io is cutoff from the internet

### What I Did

```
(venv) [user@redhat8 crossbar]$ pip3 install -r requirements-min.txt --index-url=http://internal_pypi_server:9700 --trusted-host internal_pypi_server
Ignoring twisted: markers 'sys_platform == "darwin"' don't match your environment
Ignoring twisted: markers 'sys_platform == "win32"' don't match your environment
Collecting pytest-runner==5.2 (from -r requirements-min.txt (line 1))
  Downloading http://internal_pypi_server:9700/packages/pytest_runner-5.2-py2.py3-none-any.whl
Collecting zlmdb==20.4.1 (from -r requirements-min.txt (line 2))
  Downloading http://internal_pypi_server:9700/packages/zlmdb-20.4.1.tar.gz (129kB)
    100% |████████████████████████████████| 133kB 33.7MB/s
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/pytest-runner/: [Errno 101] Network is unreachable -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [Errno 101] Network is unreachable -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    ....SNIP....
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5w4ezhz4/zlmdb/


requirements-min.txt

pytest-runner==5.2
zlmdb==20.4.1
setuptools==53.0.0
setuptools_scm==5.0.1
....SNIP...
```

**Comment by oberstet** [comment]
just remove your internal server and install from pypi :  [Errno 101] Network is unreachable

**Comment by vaibhav-rbs** [comment]
wish we can do that, Linux box is cutoff from internet server because of corporate policy. is there any other way we can address this ?

**Comment by oberstet** [comment]
actually, after relooking at `setup.py`, I think it might be actually more correct to move `pytest-runner` from `setup_requirements` to `test_requirements`:

https://github.com/crossbario/zlmdb/blob/1b293f853ca1877b25dea380dc175e59522185f6/setup.py#L58

and doing that might solve your problem ...

**Comment by oberstet** [comment]
I have no clue how you could test that before we just blindly add to a new release, and you find out if an empty `setup_requirements` solves the problem in your environment. if you want to come up with a patch, cool! it definitely works without pytest-runner, so we could just give it a shot ..

**Comment by oberstet** [comment]
this is fixed via

https://github.com/crossbario/zlmdb/pull/40

released in

https://github.com/crossbario/zlmdb/tree/v22.1.2
https://pypi.org/project/zlmdb/22.1.2/
