### ISSUE TITLE
Request: please add examples

### ISSUE THREAD

**Issue by davidmcnabnz** [crossbario/zlmdb#62]
* ZLMDB version:
* Python version:
* Operating System:

### Description

I can't find any demo examples for zlmdb

### What I Did

Searched the github source

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

It might be good to create a /examples directory to the repo, and populate it with examples ranging from the simplest and most basic to examples of moderate complexity.

**Comment by oberstet** [comment]
Crossbar.io itself uses zLMDB extensively, you can find the table definitions here:

https://github.com/crossbario/cfxdb

Eg Crossbar.io supports storing PubSub publications in a persistent realm store based on eg

https://github.com/crossbario/cfxdb/blob/master/cfxdb/realmstore/_publication.py

which is then used here

https://github.com/crossbario/crossbar/blob/master/crossbar/edge/worker/realmstore.py
